

CREATE DATABASE farmacia;


CREATE TABLE clientes(

    id INT AUTO_INCREMENT PRIMARY KEY,
    Nome VARCHAR(100) NOT NULL,
    Email VARCHAR(45) UNIQUE NOT NULL,
    senha VARCHAR(16)NOT NULL,
    DATA_DE_NACIMENTO DATE NOT NULL
);


